### ISSUE TITLE
Multilevel lists support

### ISSUE THREAD

**Issue by denisvmedia** [ojroques/hugo-researcher#11]
Dear author,

thank you for your brilliant job. It all works smoothly. But I'm struggling to make a multi-level list. Is it at all possible with this template? E.g.:

- Level 1
  - Level 2
    - Level 3
- Another Level 1
  - Another Level 2

Source: 

```markdown
- Level 1
  - Level 2
    - Level 3
- Another Level 1
  - Another Level 2
 ```

P.S. I tried both `-` and `*`. Any of them didn't work. Also, they are rendered a little bit different when I try to make a multi-level list.

**Comment by denisvmedia** [comment]
We can fix it here:

https://github.com/ojroques/hugo-researcher/blob/7a6660e6e5529c9b023cb78ec8cb0bc6ca9fa4aa/assets/sass/researcher.scss#L89-L92

with something like

```scss
    .container > ul {
        padding-left: 0;
        list-style: inside;
        ul {
            padding-left: 2em;
        }
    }
```

However, I'm not a frontend guru, so there can be a more elegant solution.
