### ISSUE TITLE
Background color for code block

### ISSUE THREAD

**Issue by svretina** [ojroques/hugo-researcher#37]
The background color for a codeblock in markdown appears to be black
and the code is black as well, resulting in non-readable output.

In the css files of the theme I can spot the codeblock section which does not have
black as the background color. Other themes, output the background color normally.

**Comment by svretina** [comment]
according to this [post](https://discourse.gohugo.io/t/background-color-for-markdown-code-block-for-the-hugo-researcher-theme/47743/7?u=stamatis_vretinaris) 
the problem is solved by replacing the below snippet in the /assets/sass/researcher.scss file
```css
* {
    color: $black;
    font-family: $font-family;
    font-size: $font-size;
    line-height: 1.2;
    // background-color: lightblue;
    // background-color: #f2f2f2;
}
```

with 
```css
body {
    color: $black;
    font-family: $font-family;
    font-size: $font-size;
    line-height: 1.2;
    // background-color: lightblue;
    // background-color: #f2f2f2;
}
```
